<?php
/*
 * Do not edit this file.
 * This code was automatically generated.
 *
 * Keeps historical 'Kc' values for a block. In the future, if we need to keep
 * more historical attributes for a block, we'll either add more of these tables
 * or generalize it to hold values for different types of attributes. However,
 * we should probably not take the same approach of 'sensor_attributes' which
 * keeps multiple attributes in the same table, which ends up causing lots of
 * duplicate data. 
 * 
 * Generated on May 26, 2015 
 */

abstract class BlockKcBeanBase extends BeanBase {
    // Fields
    private $id = -1;

    /**
     * @return id 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @param id $id
     */
    public function setId($id) {
        $this->id = $id;
    }
}